### ISSUE TITLE
Use polyfill.io ?

### ISSUE THREAD

**Issue by Grsmto** [Neverbland/neverbuild#34]
https://github.com/facebookincubator/create-react-app/issues/1104

**Comment by Grsmto** [comment]
@rafaelderolez made the experience yesterday again of that being useful. You just save so much time no having to fix undebuggable IE10 issues...
I think for light/static/simple websites it's fine to have it by default and for more advanced apps we can custom polyfill it.

**Comment by piersolenski** [comment]
I agree it's awesome but I don't think it should be an integral part of the index.html, however fast it is it's still a blocking script so should use it as and when needed. It pollyfills everything the browser doesn't have by default unless otherwise specified, which can be potentially overkill. To be used as and when needed I would say - unless you want to add it but commented out by default?

**Comment by piersolenski** [comment]
Although on further thought, CRA/Neverbuild does polyfill a bunch of stuff in `config/pollyfills.js` whether we like it or not, so maybe we should remove that in favour of polyfill.io after all...

**Comment by Grsmto** [comment]
Yeah we should remove the default polyfill maybe and integrate polyfill.io
as commented out. Seems like a good solution.
It needs to be in the readme as well so people are aware they need to set
it up...

**Comment by piersolenski** [comment]
https://github.com/Neverbland/neverbuild/pull/45
